"""
Scrapers API router
"""
from fastapi import APIRouter, Depends, HTTPException, status, BackgroundTasks
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from sqlalchemy.orm.attributes import flag_modified
from typing import List
from datetime import datetime
from uuid import UUID
from urllib.parse import urlparse
import uuid
import traceback
import logging

from core.database.connection import get_db
from core.database.models import Scraper, ScrapingRun, User, ChatSession
from api.auth.dependencies import get_current_user
from api.scrapers.schemas import (
    ScraperCreate,
    ScraperUpdate,
    ScraperResponse,
    ScraperListResponse,
    ScraperRunResponse,
    ScraperTestRequest,
    ScraperTestResponse
)
from scrapers.executor import scraper_executor

logger = logging.getLogger(__name__)

router = APIRouter()


@router.post("", response_model=ScraperResponse, status_code=status.HTTP_201_CREATED)
async def create_scraper(
    scraper_data: ScraperCreate,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Create new scraper

    For MVP, this creates a scraper with placeholder config.
    In production, this would trigger the Secondary Agent workflow.
    """
    # Extract domain from URL
    try:
        parsed_url = urlparse(scraper_data.target_url)
        target_domain = parsed_url.netloc
    except Exception:
        target_domain = None

    # Create scraper with placeholder configuration
    # In production, this would be generated by Secondary Agent
    placeholder_config = {
        "status": "pending_generation",
        "message": "Scraper configuration will be generated by Secondary Agent",
        "target_url": scraper_data.target_url,
        "created_via": "chat" if scraper_data.chat_session_id else "manual"
    }

    new_scraper = Scraper(
        id=uuid.uuid4(),
        user_id=current_user.id,
        name=scraper_data.name,
        target_url=scraper_data.target_url,
        target_domain=target_domain,
        scraping_config=placeholder_config,
        status="inactive"  # Will be 'active' after Secondary Agent generates code
    )

    db.add(new_scraper)

    # If created from chat, link to chat session
    if scraper_data.chat_session_id:
        result = await db.execute(
            select(ChatSession).where(
                ChatSession.id == scraper_data.chat_session_id,
                ChatSession.user_id == current_user.id
            )
        )
        chat_session = result.scalar_one_or_none()
        if chat_session:
            chat_session.scraper_id = new_scraper.id

    await db.commit()
    await db.refresh(new_scraper)

    return new_scraper


@router.get("", response_model=List[ScraperListResponse])
async def list_scrapers(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
    status_filter: str = None
):
    """List all scrapers for current user"""
    query = select(Scraper).where(Scraper.user_id == current_user.id)

    if status_filter:
        query = query.where(Scraper.status == status_filter)

    query = query.order_by(Scraper.created_at.desc())

    result = await db.execute(query)
    scrapers = result.scalars().all()

    return scrapers


@router.get("/{scraper_id}", response_model=ScraperResponse)
async def get_scraper(
    scraper_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Get detailed scraper information"""
    result = await db.execute(
        select(Scraper).where(
            Scraper.id == scraper_id,
            Scraper.user_id == current_user.id
        )
    )
    scraper = result.scalar_one_or_none()

    if not scraper:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Scraper not found"
        )

    return scraper


@router.put("/{scraper_id}", response_model=ScraperResponse)
async def update_scraper(
    scraper_id: UUID,
    scraper_update: ScraperUpdate,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Update scraper configuration"""
    result = await db.execute(
        select(Scraper).where(
            Scraper.id == scraper_id,
            Scraper.user_id == current_user.id
        )
    )
    scraper = result.scalar_one_or_none()

    if not scraper:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Scraper not found"
        )

    # Update fields if provided
    if scraper_update.name is not None:
        scraper.name = scraper_update.name
    if scraper_update.schedule_cron is not None:
        scraper.schedule_cron = scraper_update.schedule_cron
    if scraper_update.status is not None:
        scraper.status = scraper_update.status
    if scraper_update.scraping_config is not None:
        scraper.scraping_config = scraper_update.scraping_config

    scraper.updated_at = datetime.utcnow()

    await db.commit()
    await db.refresh(scraper)

    return scraper


@router.delete("/{scraper_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_scraper(
    scraper_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Delete scraper and all associated runs"""
    result = await db.execute(
        select(Scraper).where(
            Scraper.id == scraper_id,
            Scraper.user_id == current_user.id
        )
    )
    scraper = result.scalar_one_or_none()

    if not scraper:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Scraper not found"
        )

    # Delete associated runs first
    await db.execute(
        select(ScrapingRun).where(ScrapingRun.scraper_id == scraper_id)
    )

    await db.delete(scraper)
    await db.commit()

    return None


@router.post("/{scraper_id}/test", response_model=ScraperTestResponse)
async def test_scraper(
    scraper_id: UUID,
    test_request: ScraperTestRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Test scraper execution

    For MVP, this returns mock data.
    In production, this would execute the scraper in test mode.
    """
    result = await db.execute(
        select(Scraper).where(
            Scraper.id == scraper_id,
            Scraper.user_id == current_user.id
        )
    )
    scraper = result.scalar_one_or_none()

    if not scraper:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Scraper not found"
        )

    # Mock response for MVP
    # In production, this would run the actual scraper
    return ScraperTestResponse(
        success=True,
        records_scraped=test_request.sample_size,
        sample_data=[
            {
                "title": f"Sample Product {i}",
                "price": 29.99 + i,
                "url": f"{scraper.target_url}/product-{i}"
            }
            for i in range(test_request.sample_size)
        ],
        errors=[],
        execution_time=2.5
    )


async def _execute_scraper_background(
    run_id: UUID,
    scraper_id: UUID,
    user_id: UUID,
    db_url: str
):
    """
    Background task for scraper execution

    This runs asynchronously after the API returns.
    Updates the scraping_runs table with results.

    Args:
        run_id: ScrapingRun UUID
        scraper_id: Scraper UUID
        user_id: User UUID
        db_url: Database connection string
    """
    from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
    from sqlalchemy.orm import sessionmaker

    logger.info(f"[BACKGROUND] Starting execution for run {run_id}")

    # Ensure database URL uses async driver (asyncpg)
    # Replace psycopg2 or generic postgresql with asyncpg
    if db_url.startswith("postgresql://"):
        db_url = db_url.replace("postgresql://", "postgresql+asyncpg://", 1)
    elif db_url.startswith("postgresql+psycopg2://"):
        db_url = db_url.replace("postgresql+psycopg2://", "postgresql+asyncpg://", 1)

    # Create new DB session for background task
    engine = create_async_engine(db_url, echo=False)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with async_session() as session:
        try:
            # Update status to running
            result = await session.execute(
                select(ScrapingRun).where(ScrapingRun.id == run_id)
            )
            run = result.scalar_one_or_none()

            if not run:
                logger.error(f"[BACKGROUND] Run {run_id} not found in database")
                return

            run.status = "running"
            run.started_at = datetime.utcnow()
            await session.commit()

            logger.info(f"[BACKGROUND] Updated run status to 'running'")

            # Execute scraper
            execution_result = await scraper_executor.execute_scraper(
                user_id=user_id,
                scraper_id=scraper_id,
                run_id=run_id
            )

            logger.info(f"[BACKGROUND] Execution completed: {execution_result.to_dict()}")

            # Update run record with results
            run.completed_at = datetime.utcnow()

            if execution_result.success:
                run.status = "success"
                run.records_scraped = execution_result.records_scraped
                run.output_url = execution_result.output_url
                logger.info(f"[BACKGROUND] Success: {execution_result.records_scraped} records scraped")
            else:
                run.status = "failed"
                run.error_message = execution_result.error_message
                logger.error(f"[BACKGROUND] Failed: {execution_result.error_message}")

            await session.commit()

            # Update scraper's last_run_at timestamp
            scraper_result = await session.execute(
                select(Scraper).where(Scraper.id == scraper_id)
            )
            scraper = scraper_result.scalar_one_or_none()

            if scraper:
                scraper.last_run_at = datetime.utcnow()
                if execution_result.success:
                    scraper.last_success_at = datetime.utcnow()
                await session.commit()

            logger.info(f"[BACKGROUND] Completed execution for run {run_id}")

        except Exception as e:
            logger.error(f"[BACKGROUND] Unexpected error in background task: {e}")
            logger.error(traceback.format_exc())

            # Try to update run status to failed
            try:
                result = await session.execute(
                    select(ScrapingRun).where(ScrapingRun.id == run_id)
                )
                run = result.scalar_one_or_none()

                if run:
                    run.status = "failed"
                    run.completed_at = datetime.utcnow()
                    run.error_message = f"Background task error: {str(e)}"
                    await session.commit()
            except Exception as db_error:
                logger.error(f"[BACKGROUND] Failed to update error status: {db_error}")

        finally:
            await engine.dispose()


@router.post("/{scraper_id}/run", response_model=ScraperRunResponse, status_code=status.HTTP_202_ACCEPTED)
async def run_scraper(
    scraper_id: UUID,
    background_tasks: BackgroundTasks,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Trigger manual scraper run

    This endpoint:
    1. Creates a run record with status="queued"
    2. Returns immediately (202 Accepted)
    3. Executes scraper in background
    4. Updates run status when complete

    Client should poll GET /scrapers/{id}/runs/{run_id} for status.
    """
    result = await db.execute(
        select(Scraper).where(
            Scraper.id == scraper_id,
            Scraper.user_id == current_user.id
        )
    )
    scraper = result.scalar_one_or_none()

    if not scraper:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Scraper not found"
        )

    # Check if scraper has generated code
    config = scraper.scraping_config or {}
    if not config.get("generated_code"):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Scraper code not yet generated. Please generate code first."
        )

    # Create scraping run record
    new_run = ScrapingRun(
        id=uuid.uuid4(),
        scraper_id=scraper_id,
        status="queued",
        created_at=datetime.utcnow()
    )

    db.add(new_run)
    await db.commit()
    await db.refresh(new_run)

    logger.info(f"[RUN ENDPOINT] Created run {new_run.id} for scraper {scraper_id}")

    # Add background task for execution
    from core.config import settings
    background_tasks.add_task(
        _execute_scraper_background,
        run_id=new_run.id,
        scraper_id=scraper_id,
        user_id=current_user.id,
        db_url=settings.DATABASE_URL
    )

    logger.info(f"[RUN ENDPOINT] Queued background execution for run {new_run.id}")

    return new_run


@router.get("/{scraper_id}/runs", response_model=List[ScraperRunResponse])
async def get_scraper_runs(
    scraper_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
    limit: int = 50
):
    """Get execution history for a scraper"""
    # Verify scraper belongs to user
    result = await db.execute(
        select(Scraper).where(
            Scraper.id == scraper_id,
            Scraper.user_id == current_user.id
        )
    )
    scraper = result.scalar_one_or_none()

    if not scraper:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Scraper not found"
        )

    # Get runs
    result = await db.execute(
        select(ScrapingRun)
        .where(ScrapingRun.scraper_id == scraper_id)
        .order_by(ScrapingRun.created_at.desc())
        .limit(limit)
    )
    runs = result.scalars().all()

    return runs


@router.get("/{scraper_id}/runs/{run_id}", response_model=ScraperRunResponse)
async def get_scraper_run(
    scraper_id: UUID,
    run_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Get details for a specific scraping run

    Use this endpoint to poll for run status updates.
    Status values: queued, running, success, failed
    """
    # Verify scraper belongs to user
    result = await db.execute(
        select(Scraper).where(
            Scraper.id == scraper_id,
            Scraper.user_id == current_user.id
        )
    )
    scraper = result.scalar_one_or_none()

    if not scraper:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Scraper not found"
        )

    # Get specific run
    result = await db.execute(
        select(ScrapingRun).where(
            ScrapingRun.id == run_id,
            ScrapingRun.scraper_id == scraper_id
        )
    )
    run = result.scalar_one_or_none()

    if not run:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Run not found"
        )

    return run


async def _generate_scraper_background(scraper_id: UUID, user_id: UUID, db_url: str):
    """Background task running the Secondary Agent generation workflow.

    Mirrors `_execute_scraper_background`: generation takes minutes (a 30-iteration
    agent loop), far beyond the frontend's 2-minute HTTP timeout — running it
    inside the request made the browser error out while the backend kept working.
    The frontend polls scraper status every 5s, so all results flow through the DB.
    """
    from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
    from sqlalchemy.orm import sessionmaker
    from agents.secondary.agent import SecondaryAgent

    if db_url.startswith("postgresql://"):
        db_url = db_url.replace("postgresql://", "postgresql+asyncpg://", 1)
    elif db_url.startswith("postgresql+psycopg2://"):
        db_url = db_url.replace("postgresql+psycopg2://", "postgresql+asyncpg://", 1)

    engine = create_async_engine(db_url, echo=False)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with async_session() as db:
        result = await db.execute(select(Scraper).where(Scraper.id == scraper_id))
        scraper = result.scalar_one_or_none()
        if not scraper:
            logger.error(f"[GENERATION BACKGROUND] Scraper {scraper_id} not found")
            await engine.dispose()
            return
        config = scraper.scraping_config or {}
        data_fields = config.get("data_fields", [])
        special_requirements = config.get("special_requirements")

        try:
            logger.info("[GENERATION BACKGROUND] Initializing Secondary Agent...")
            agent = SecondaryAgent()
            result = await agent.generate_scraper(
                user_id=str(user_id),
                scraper_id=str(scraper_id),
                target_url=scraper.target_url,
                data_fields=data_fields,
                special_requirements=special_requirements
            )
            logger.info(f"[GENERATION BACKGROUND] Agent returned: success={result.get('success')}")

            if result.get("success") and result.get("scraper_code"):
                # Persist the final code at the executor's contract path: the
                # agent names its working scripts freely (anhoch_scraper.py,
                # *_improved.py, ...) but ScraperExecutor runs exactly
                # scrapers/{user_id}/{scraper_id}/scraper.py.
                try:
                    from pathlib import Path
                    scraper_dir = Path("scrapers") / str(user_id) / str(scraper_id)
                    scraper_dir.mkdir(parents=True, exist_ok=True)
                    (scraper_dir / "scraper.py").write_text(
                        result["scraper_code"], encoding="utf-8")
                    logger.info(f"[GENERATION BACKGROUND] Final code persisted to "
                                f"{scraper_dir / 'scraper.py'}")
                except OSError as e:
                    logger.error(f"[GENERATION BACKGROUND] Could not write "
                                 f"scraper.py: {e} — runs will fail until fixed")
                scraper.scraping_config = {
                    **config,
                    "generated_code": result["scraper_code"],
                    "test_results": result.get("test_results"),
                    "analysis": result.get("analysis"),
                    "reasoning_log": result.get("reasoning_log", []),
                    "generation_completed_at": datetime.utcnow().isoformat(),
                    "tool_calls": result.get("tool_calls", []),
                    "iterations": result.get("iterations", 0),
                    "final_message": result.get("final_message", "")
                }
                scraper.status = "active"
            else:
                scraper.scraping_config = {
                    **config,
                    "error": result.get("message", "Generation failed"),
                    "reasoning_log": result.get("reasoning_log", []),
                    "generation_failed_at": datetime.utcnow().isoformat(),
                    "tool_calls": result.get("tool_calls", [])
                }
                scraper.status = "failed"
            await db.commit()
            logger.info(f"[GENERATION BACKGROUND] Completed, status={scraper.status}")
        except Exception as e:
            logger.error(f"[GENERATION BACKGROUND] {type(e).__name__}: {e}\n"
                         f"{traceback.format_exc()}")
            scraper.status = "failed"
            scraper.scraping_config = {
                **config,
                "error": str(e),
                "error_type": type(e).__name__,
                "traceback": traceback.format_exc(),
                "generation_failed_at": datetime.utcnow().isoformat()
            }
            await db.commit()
        finally:
            await engine.dispose()


@router.post("/{scraper_id}/generate", status_code=status.HTTP_202_ACCEPTED)
async def generate_scraper_code(
    scraper_id: UUID,
    background_tasks: BackgroundTasks,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Trigger Secondary Agent to generate scraper code

    This endpoint initiates the code generation workflow:
    1. Fetches scraper configuration
    2. Triggers Secondary Agent to analyze website
    3. Generates Botasaurus scraping code
    4. Tests the generated code
    5. Updates scraper with generated code

    Returns immediately with acceptance status.
    Actual generation happens asynchronously.
    """
    # Get scraper
    result = await db.execute(
        select(Scraper).where(
            Scraper.id == scraper_id,
            Scraper.user_id == current_user.id
        )
    )
    scraper = result.scalar_one_or_none()

    if not scraper:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Scraper not found"
        )

    # Mark as generating, then hand off to a background task — the agent loop
    # takes minutes and must not run inside the request (the frontend times out
    # at 2 minutes and polls scraper status instead).
    scraper.status = "generating"
    await db.commit()

    logger.info("="*80)
    logger.info(f"[SCRAPER GENERATION ENDPOINT] Queuing code generation")
    logger.info(f"User ID: {current_user.id} | Scraper ID: {scraper_id} | "
                f"Target URL: {scraper.target_url}")
    logger.info("="*80)

    from core.config import settings
    background_tasks.add_task(
        _generate_scraper_background,
        scraper_id=scraper_id,
        user_id=current_user.id,
        db_url=settings.DATABASE_URL
    )

    return {
        "scraper_id": str(scraper_id),
        "status": "generating",
        "message": "Code generation started — poll scraper status for completion"
    }
